name: Code Style Check

on:
  push:

jobs:
  style_check:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .

      - name: Run Prettier
        run: npx prettier --check .

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: style-check-results
          path: |
            .eslintrc.js
            .prettierrc.js
            .eslintignore
